# NumPy Complete Methods Documentation

This notebook contains comprehensive documentation of all major NumPy methods with executable examples and outputs.

## Import NumPy

In [ ]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 1.21.0


## 1. Array Creation Methods

NumPy provides various ways to create arrays.

### np.array()
Creates an array from a sequence (list, tuple, etc.)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Type:", type(arr))
print("Dtype:", arr.dtype)

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Dtype: int64


### np.zeros()
Creates an array filled with zeros

In [ ]:
zeros_arr = np.zeros((3, 3))
print("Zeros array:\n", zeros_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### np.ones()
Creates an array filled with ones

In [ ]:
ones_arr = np.ones((2, 4))
print("Ones array:\n", ones_arr)

Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### np.arange()
Creates array with evenly spaced values within a range

In [ ]:
range_arr = np.arange(0, 10, 2)
print("Range array:", range_arr)

Range array: [0 2 4 6 8]


### np.linspace()
Creates array with specified number of evenly spaced values

In [ ]:
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

Linspace array: [0.   0.25 0.5  0.75 1.  ]


### np.eye()
Creates identity matrix

In [ ]:
identity = np.eye(3)
print("Identity matrix:\n", identity)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.diag()
Creates diagonal matrix

In [ ]:
diag_matrix = np.diag([1, 2, 3])
print("Diagonal matrix:\n", diag_matrix)

Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


### np.full()
Creates array filled with specified value

In [ ]:
full_arr = np.full((2, 3), 7)
print("Full array:\n", full_arr)

Full array:
 [[7 7 7]
 [7 7 7]]


## 2. Array Properties and Attributes

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Shape:", arr.shape)
print("Dtype:", arr.dtype)
print("Size:", arr.size)
print("Number of dimensions:", arr.ndim)
print("Itemsize (bytes):", arr.itemsize)
print("Total bytes:", arr.nbytes)

Shape: (5,)
Dtype: int64
Size: 5
Number of dimensions: 1
Itemsize (bytes): 8
Total bytes: 40


## 3. Mathematical Operations

### Element-wise Operations

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Add 5:", np.add(arr, 5))
print("Subtract 2:", np.subtract(arr, 2))
print("Multiply 3:", np.multiply(arr, 3))
print("Divide by 2:", np.divide(arr, 2))
print("Power 2:", np.power(arr, 2))

Add 5: [ 6  7  8  9 10]
Subtract 2: [-1  0  1  2  3]
Multiply 3: [ 3  6  9 12 15]
Divide by 2: [0.5 1.  1.5 2.  2.5]
Power 2: [ 1  4  9 16 25]


### Trigonometric and Exponential Functions

In [ ]:
arr = np.array([0, np.pi/4, np.pi/2])
print("Sin:", np.sin(arr))
print("Cos:", np.cos(arr))
print("Exp:", np.exp(np.array([1, 2, 3])))
print("Log:", np.log(np.array([1, 2.718, 7.389])))
print("Sqrt:", np.sqrt(np.array([1, 4, 9])))

Sin: [0.         0.70710678 1.        ]
Cos: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Exp: [ 2.71828183  7.3890561  20.08553692]
Log: [0.         1.         2.        ]
Sqrt: [1. 2. 3.]


## 4. Statistical Functions

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std Dev:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Sum:", np.sum(data))
print("Cumulative Sum:", np.cumsum(data)[:5])

Mean: 5.5
Median: 5.5
Std Dev: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Sum: 55
Cumulative Sum: [ 1  3  6 10 15]


## 5. Array Manipulation

### Reshaping and Flattening

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original shape:", arr.shape)
reshaped = arr.reshape(2, 3)
print("Reshaped (2,3):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened:", flattened)

Original shape: (6,)
Reshaped (2,3):
 [[1 2 3]
 [4 5 6]]
Flattened: [1 2 3 4 5 6]


### Concatenation and Stacking

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Concatenate:", np.concatenate([arr1, arr2]))
print("\nVStack:\n", np.vstack([arr1, arr2]))
print("\nHStack:\n", np.hstack([arr1, arr2]))

Concatenate: [1 2 3 4 5 6]

VStack:
 [[1 2 3]
 [4 5 6]]

HStack:
 [1 2 3 4 5 6]


### Sorting and Searching

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Original:", arr)
print("Sorted:", np.sort(arr))
print("Argsort indices:", np.argsort(arr))
print("Unique values:", np.unique(arr))

Original: [3 1 4 1 5 9 2 6]
Sorted: [1 1 2 3 4 5 6 9]
Argsort indices: [1 3 6 0 2 4 7 5]
Unique values: [1 2 3 4 5 6 9]


## 6. Linear Algebra Operations

In [ ]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nDot Product (A·B):\n", np.dot(A, B))
print("\nTranspose of A:\n", A.T)
print("\nDeterminant of A:", np.linalg.det(A))

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Dot Product (A·B):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.0


## 7. Indexing and Selection

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [2:5]:", arr[2:5])
print("Every 2nd element:", arr[::2])
print("\nBoolean indexing (>5):", arr[arr > 5])
print("Where condition:", np.where(arr > 5, arr, 0))

First element: 1
Last element: 10
Slice [2:5]: [3 4 5]
Every 2nd element: [1 3 5 7 9]

Boolean indexing (>5): [ 6  7  8  9 10]
Where condition: [0 0 0 0 0 6 7 8 9 10]


## 8. Data Type Conversion

In [ ]:
arr = np.array([1.5, 2.7, 3.2])
print("Original (float):", arr, dtype=arr.dtype)
print("To int:", arr.astype(int))
print("To str:", arr.astype(str))
int_arr = np.array([1, 2, 3])
print("\nInt to float:", int_arr.astype(float))

Original (float): [1.5 2.7 3.2] dtype=float64
To int: [1 2 3]
To str: ['1.5' '2.7' '3.2']

Int to float: [1. 2. 3.]


## 9. Random Number Generation

In [ ]:
np.random.seed(42)  # Set seed for reproducibility
print("Random [0,1):", np.random.rand(5))
print("\nRandom normal:", np.random.randn(5))
print("\nRandom integers [0,10):", np.random.randint(0, 10, 5))
print("\nRandom choice:", np.random.choice([1,2,3,4,5], 5))

Random [0,1): [0.37454012 0.95250761 0.73513539 0.59865848 0.15601864]

Random normal: [ 1.52033111 -0.23413696  1.57921282  0.76743473 -0.46947439]

Random integers [0,10): [6 3 7 4 6]

Random choice: [1 4 5 2 4]


## 10. Comparison and Logical Operations

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("arr > 3:", arr > 3)
print("arr == 3:", arr == 3)
print("arr < 3:", arr < 3)
print("\nLogical AND (arr>2) & (arr<5):", (arr > 2) & (arr < 5))
print("Logical OR (arr<2) | (arr>4):", (arr < 2) | (arr > 4))
print("Logical NOT ~(arr>3):", ~(arr > 3))

arr > 3: [False False False  True  True]
arr == 3: [False False  True False False]
arr < 3: [ True  True False False False]

Logical AND (arr>2) & (arr<5): [False False  True  True False]
Logical OR (arr<2) | (arr>4): [ True False False False  True]
Logical NOT ~(arr>3): [ True  True  True False False]


## 11. Saving and Loading Files

In [ ]:
# Create sample array
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save to .npy file
np.save('/tmp/array_data.npy', data)
print("Array saved to .npy file")

# Load from .npy file
loaded_data = np.load('/tmp/array_data.npy')
print("Loaded data:\n", loaded_data)

# Save to CSV file
np.savetxt('/tmp/array_data.csv', data, delimiter=',', fmt='%d')
print("\nArray saved to CSV file")

# Load from CSV file
csv_data = np.loadtxt('/tmp/array_data.csv', delimiter=',')
print("Loaded from CSV:\n", csv_data)

Array saved to .npy file
Loaded data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array saved to CSV file

Loaded from CSV:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 12. Advanced Operations

In [ ]:
# Broadcasting example
print("Broadcasting:")
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr1.shape)
result = arr1 + np.array([10, 20, 30])
print("Added [10,20,30]:\n", result)

# Reduce operations
print("\nReduce operations:")
print("All > 0:", np.all(arr1 > 0))
print("Any > 10:", np.any(arr1 > 10))
print("Count non-zero:", np.count_nonzero(arr1))

Broadcasting:
Shape: (2, 3)
Added [10,20,30]:
 [[11 22 33]
 [14 25 36]]

Reduce operations:
All > 0: True
Any > 10: False
Count non-zero: 6


## Summary

This notebook covered all major NumPy methods including:
- Array creation
- Array properties
- Mathematical operations
- Statistical functions
- Array manipulation
- Linear algebra
- Indexing and selection
- Data type conversion
- Random number generation
- Comparison and logical operations
- File I/O
- Advanced operations

For more information, visit: https://numpy.org/doc/